version: "3"

# Test compose file for building a stachebox stack
services:

elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.max_content_length=1024mb
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=5t4ch380x!
    ports:
      - "9200:9200"
      - "9300:9300"

  stachebox:
    image: ortussolutions/stachebox:latest
    ports:
      - "61686:8080"
    environment:
      ENVIRONMENT: production
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: "5t4ch380x!"
      STACHEBOX_ADMIN_EMAIL: stachebox@ortussolutions.com
      STACHEBOX_ADMIN_PASSWORD: "5t4ch380x!"
      HEALTHCHECK_URI: http://127.0.0.1:8080/?healthcheck=true
    restart: on-failure:5

volumes:
  elasticsearch-data: